### ISSUE TITLE
Cannot open application (Release)

### ISSUE THREAD

**Issue by SSUPII** [skauertz/QCounter#1]
```
$ ./QCounter.sh
./QCounter: error while loading shared libraries: ./lib/libQt5Widgets.so.5: file too short
```

**Comment by skauertz** [comment]
What distribution are you using? It works fine here for me on Ubuntu 22.04.

Have you verified that all the links in the ./lib subdirectory have been correctly preserved after unzipping?

**Comment by SSUPII** [comment]
> What distribution are you using? It works fine here for me on Ubuntu 22.04.
> 
> Have you verified that all the links in the ./lib subdirectory have been correctly preserved after unzipping?

Debian 12.1 Bookworm x86_64.

Apparently uncompressing was the issue. I had this exact error trying to open the MatLab R2023b install script with a different library after uncompressing it with Ark. Using `unzip` instead preserves the files properly. Yet under the `lib` folder when uncompressed with Ark all files are there and all have the correct size. But these files are not valid unless extracted using `unzip`

https://mathworks.com/matlabcentral/answers/514883-install_unix-error-while-loading-shared-libraries-and-libexpat-so-1-file-too-short-2020a

**Comment by skauertz** [comment]
Yes, I noticed before when unzipping with certain applications the links are not properly preserved. Glad you figure it out.
